### ISSUE TITLE
Child-Parent color coding for cards

### ISSUE THREAD

**Issue by Duke4233** [ZachRiegel/cards#21]
For a card with a parent and a child have the parent background color be one color and then any children be a different color. 

-IE parent grey background and all children have a white background.
-Add a small border to a child block. 
Example card: Incendiary Arrow
Quiver and Make a ranged weapon attack line would have the same colored bakc ground and then the three childern would have a a common color with eachother but different than the "parent".

**Comment by ZachRiegel** [comment]
Talked this over with Kevin, we are going to try this, but are unsure if this will stick.

**Comment by ZachRiegel** [comment]
Tried it, changes are on the live site right now, not sure if I'm a fan, but we'll talk about it.

**Comment by ZachRiegel** [comment]
I think the biggest issue is that the grey/white shading is conveying the same information that the child icons are and that it makes the cards seem "bulkier" with the large chunks of the same-colored areas stuck together.

Maybe it improves the readability of some of the quiver effects, but I have a hard time telling tbh.

**Comment by ZachRiegel** [comment]
Reverted back to original formatting per discussion.
