### ISSUE TITLE
Design and formalize Legionnaire/elemental cards

### ISSUE THREAD

**Issue by KevinALanders** [ZachRiegel/cards#23]
0 of 8 designed
0 of 8 formalized

**Comment by KevinALanders** [comment]
design decisions 
always have at least 1 follow through 
card Ideas
aero
1. redirect: reaction to ranged weapon attacks that miss
2. an attack with an ability with a follow through to shift
hydro
1. shitty attack, follow through to taking damage heal #*x
2. ice shield, require shield set wet on self, while buffed by this card and wet gain phys resist + fire resist 
pyro
1. set smolder and clear some debuffs, follow through: get hit, deal fire back
2. attack deal phys, follow through at end of turn deal #*x fire damage to that creature no attack 
geo
1.  attack. follow through to rolling a defense die, set die to max
2.  Tar foe: attack against moto, on hit deal earth damage and set slick(oil version of caked), slowed and impaired

**Comment by ZachRiegel** [comment]
aero
1. Cost 1 aero. redirect: reaction to ranged weapon attacks that miss. Cost: 1 air. Range 0-3, 0-1 of self for redirect.
2. Cost 1 any. Weapon attack. On hit, @weaponModifier physical, air 8.  Follow through before start of your turn to shift 1.
hydro
4. Cost 1: any. Weapon attack, @weaponModifier physical 6 water. Follow through when you take damage heal 4*x.
5. Cost 1 hydro. ice shield, requires a shield set wet on self, while buffed by this card (4 turns) and wet gain 5 phys resist + fire resist.
pyro
7. Rebuking Flames: Cost 1 fire. Set smolder 3. Clear slowed, wet, fatigued, dazed, Follow through X: when you are hit by a melee attack, deal 3*X + @spellModifier fire damage.
8. Fire Stabby Stab: Cost 1 any. Make weapon attack deal @weaponModifier phys damage. Follow through at end of this turn deal 5*x fire damage to that creature (No second attack needed).
geo
10. Make a melee weapon attack. On hit deal, 7 + @weaponModifier physical damage. Follow through to being hit with a melee weapon attack, ward yourself.
11. Pitch: Cost 1 earth. Make a ranged spell attack 0-1 against target's motorics defense, on hit deal 7 + @spellModifier earth damage. If a creature took earth damage from this, set tarred 3, slowed 1, and impaired 1.

**Comment by Confusicous** [comment]
Theoretical Aeromancer/Legionnaire card names: 
1. Deflecting Gust: redirect reaction
2. Drifting Strike: weapon attack and move

These are pretty generic/formulaic so if there are more creative ideas I'm open.

**Comment by ZachRiegel** [comment]
aero
Deflecting Gust: Cost 1 aero. redirect: reaction to ranged weapon attacks that miss. Cost: 1 air. Range 0-3, 0-1 of self for redirect.
Drifting Strike: Cost 1 any. Weapon attack. On hit, @weaponModifier physical, air 8. Follow through before the start of your next turn to shift 1.
hydro
Healing Balm: Cost 1: any. Battle tempo (@weaponModifier + 6 water). Follow through: Before you start your next turn. heal 4*x.
Mantle of Dew: Cost 1 hydro. Requires a shield set wet on self, while buffed by this card (4 turns) and wet gain 5 phys resist + fire resist.
pyro
Rebuking Flames: Cost 1 fire. Set smolder 3. Clear slowed, wet, fatigued, dazed, Follow through X: when you are hit by a melee attack, deal 3*X + @spellModifier fire damage.
Fire Stabby Stab: Cost 1 any. Make weapon attack deal @weaponModifier phys damage. Follow through at end of this turn deal 5*x fire damage to that creature (No second attack needed).
geo
Jab: Make a melee weapon attack. On hit deal, 7 + @weaponModifier physical damage. Follow through to being hit with an attack against your armor defense, ward yourself.
Pitch: Cost 1 earth. Make a ranged spell attack 0-1 against target's motorics defense, on hit deal 7 + @spellModifier earth damage. If a creature took earth damage from this, set tarred 3, slowed 1, and impaired 1.

Note: switching all legionnaire cards to use new battle tempo mechanic

**Comment by ZachRiegel** [comment]
aero
Deflecting Gust: Cost 1 aero. redirect: reaction to ranged weapon attacks that hit. Range 0-3, 0-1 of self for redirect.

Warmagic: Breeze: Cost 1 any. Weapon attack. On hit, @weaponModifier physical, air 8. Plan "Windborne Stride" and "Quell".

Windborne Stride: Enact X before the start of your turn. Shift 1.
Quell: Enact X at the end of your turn. Remove X tokens from your zone.

hydro
Warmagic: Pond: Cost 1: any. make an attack against the armor defense of target creature for @weaponModifier + 6 water damage and prime it. Plan Healing Blam and Cleanse.

Healing Balm: Enact X: Before you start your next turn. heal 4x.
Cleanse: Enact X: End of turn. Clear up to 1 effect from the creature target creature primed by Warmagic Pond. Set wet on the targeted creature.

Mantle of Dew: Cost 1 hydro. Requires a shield set wet on self, while buffed by this card (4 turns) and wet gain 5 phys resist + fire resist.

pyro
Rebuking Flames: Cost 1 fire. Set smolder 3. Clear slowed, wet, fatigued, dazed. Plan Fiery Rebuke.

Fiery Rebuke: Enact X: When you are hit by a melee attack, deal 3X + @spellModifier fire damage.

Warmagic: Ember: Cost 1 any. Make a weapon attack against the armor defense of target creature for @weaponModifier phys damage and prime it. Plan "Detonate" and "".

Detonate: Enact X: Deal 6*X fire damage to target creature primed by "Warmagic: Ember".
Rousing Flames: Enact X: Before the start of your turn. Draw a card from your reserves.

geo
Warmagic: Copse: Any 1: Make a melee weapon attack against the armor defense of target creature. On hit deal, @weaponModifier physical damage and prime it. Plan "" and "".

Briarthorn: Enact X: At the end of your turn, deal 3*X earth damage to target creature primed by "Warmagic: Copse". If a creature took damage in this way, set bleed 3 on it.
Gnarled Hide: Enact X: Before the start of your turn, set your armor and physique defense dice to their maximum value.


Pitch: Cost 1 earth. Make a ranged spell attack 0-1 against target's motorics defense, on hit deal 7 + @spellModifier earth damage. If a creature took earth damage from this, set tarred 3, slowed 1, and impaired 1.

**Comment by ZachRiegel** [comment]
Done, cards are live on site.
