### ISSUE TITLE
Design and formalize Aeromancer/Hydromancer 

### ISSUE THREAD

**Issue by KevinALanders** [ZachRiegel/cards#24]
0 of 2 designed
0 of 2 formalized

**Comment by ZachRiegel** [comment]
2 of 2 designed
0 of 2 formalized

 Chill Wind: Cost air 1/ water 1. Make a spell attack against the physique defense of each creature in 3 target contiguous zones. On hit deal 2 + spellModifier ice damage. If a creature took damage from this, set slowed 1 and it must discard 1 card. Convert up to one water token in each of those zones to an ice token. 

Misty Escape: Cost 0. Reaction before you would be hit with an attack. Ward each creature in your zone. Shift yourself up to one zone.

**Comment by ZachRiegel** [comment]
done
