### ISSUE TITLE
Design and formalize Aeromancer/Pyromancer

### ISSUE THREAD

**Issue by KevinALanders** [ZachRiegel/cards#25]
0 of 2 designed
0 of 2 formalized

**Comment by ZachRiegel** [comment]
2 of 2 designed

**Comment by ZachRiegel** [comment]
This is next

**Comment by KevinALanders** [comment]
Spit balling ideas
Backdraft
Cost 1 fire, target zone most likely, deal som fire damage, clear fire tokens, deal bonus fire damage per token cleared
"Haste mark I"
Cost 1 air, target ally[you are an ally of yourself], buff 3, draw an extra card (lose 2 now, gain three over time), plus a rider like:
 when applied clear some effects like slow and fatigue(think inner fire), maybe make immune I'm unsure, 
  Or at start of turn move 1 free/when you discard a card to move a zone you may move up to two zones

**Comment by KevinALanders** [comment]
Backdraft has been changed to cost 1 air
Haste mark 1 has been rejected
a lightning damage dealing card that converts earth tokens to fire tokens has been suggested

**Comment by ZachRiegel** [comment]
As an aside, the notetaking here is horrendous, these were not implementable as written. Given that no one thought these needed doing, this should've been in a better state or revisited.

**Comment by ZachRiegel** [comment]
done
