### ISSUE TITLE
Design and formalize Aeromancer/Geomancer

### ISSUE THREAD

**Issue by KevinALanders** [ZachRiegel/cards#26]
0 of 2 designed
0 of 2 formalized

**Comment by Confusicous** [comment]
Conceptually encompassing Sand/dust clouds, Magnetism, Sonic type things

**Comment by Confusicous** [comment]
Reverberating Blast: 1 Any (range 1-2)
Make a spell attack against each creature's physique defense in target zone. 
On hit deal 3 + Spell Mod Vibration damage. If they took Vibration damage from this card set Dazed 1 and Impaired 1.

Choking Smog: 1 Geo (range 0)
Target Triangle 
Make an attack against each other creature's physique defense in targeted zones.
On hit deal 2 + Spell Mod Decay Damage.
If they took Decay damage from this set Enfeebled 1 and Poison 4.

**Comment by ZachRiegel** [comment]
10/10, especially compared to the aero/pyro.

**Comment by ZachRiegel** [comment]
done
