### ISSUE TITLE
Design and formalize Hydromancer/Pyromancer

### ISSUE THREAD

**Issue by KevinALanders** [ZachRiegel/cards#27]
0 of 2 designed
0 of 2 formalized

**Comment by KevinALanders** [comment]
"Hydrothermic Siphon" cost 1 Hydro 1 Pyro
range 0-2, clear target token,
if that token was a water token, restore 13+spell mod health to target creature.
if that token was a fire token, make a spell attack against the armor defense of target creature
-->on hit, deal 13+spell mod damage to the hit creature

"Circulate"cost 0
range 0-2, move up to 3 water or fire tokens one zone

**Comment by ZachRiegel** [comment]
done
