### ISSUE TITLE
Design and formalize Hydromancer/Geomancer

### ISSUE THREAD

**Issue by KevinALanders** [ZachRiegel/cards#28]
0 of 2 designed
0 of 2 formalized

**Comment by Confusicous** [comment]
Mud Ball: 1 Earth (range 1-2)
    Make a Ranged Spell attack against each creature's motorics defense in target zone
       on hit deal 3 + Spell Mod Mud damage. 
       If damage is taken set Muddied 3
       If damage taken set Muddied 3, debuff: "While Muddied movement counts as in difficult terrain."

Siphon Essence: 1 Water (range 0-2)
   Make a Ranged Spell attack against a target creature's Physique defense
       on hit deal 3 + Spell Mod Decay damage.
       If a creature took damage from this heal a target X, where X is the Decay damage dealt.

**Comment by ZachRiegel** [comment]
done
